### ISSUE TITLE
Concern about the correlation between free space and TRIM frequency

### ISSUE THREAD

**Issue by phocean** [chmatse/SSDcronTRIM#5]
Nice work, thanks.

However, I am skeptical on your assumption, when you adjust the cron frequency according to the partition free space.

As far as I know, fragmentation happens over time and is not really correlated to free space.
It is correlated to the subsequent number of write operations that happen on the disk, which is a very different notion.

So even with a lot of free space, but a high number of write / erase cycles, the SSD may use up all its blocks anyway, leading to performance loss.
Such a disk would benefit from frequent fstrim checks, whereas your script would do it only once a month.

**Comment by chmatse** [comment]
Hello phocean. Sorry for the delayed Answer, i really missed your issue :-( Big sorry for that!

This would become a loooong answer, so instead of writing a lot of text i suggest you read the following arstechnica article:

http://arstechnica.com/gadgets/2015/04/ask-ars-my-ssd-does-garbage-collection-so-i-dont-need-trim-right/

To make a long story short: TRIM is never a requirement, but it always helps, and you’re always better off with it than without it. Modern SSD Drives have a garbage collection implemented which makes sure that you will never eat up your whole disk.

For my understanding it is true that in a high write situation the performance will go down, because the data has to be read first, deleted/re-arranged and then written back to the disk. Whereas on a trimmed disk the data can just be written to the disk.

But if you really have a permanent high write on the disk, then you should consider to change from SSD to a SATA Disk. In a normal life your system is mostly in a reading and seldom in a writing state.

Therefore i guess it should be sufficient to trim the disk only once a month.

**Comment by phocean** [comment]
Hello chmatse,

No problem at all ;-)
Thanks for the pointer to arstechnica, it is very well explained indeed.

That said, it is true that my laptop usage is not a typical one. I use a lot of VM, doing quite a lot of writes, and then often juggle with snapshots.
It probably creates/deletes tens of gigabytes a day, so I think in such an environment TRIM makes a lot of sense.
And, no, I don't want to go back to a hard drive, as it is so fast ! :-D
By the way, it will be interesting to see the lifetime of my SSD (yes, I do make backups)...
