### ISSUE TITLE
Cronjobs have no execute permission

### ISSUE THREAD

**Issue by chmatse** [chmatse/SSDcronTRIM#7]
Received an E-mail from Christian Dysthe which brought to my attention, that the installed cronjobs have no execute permission

> I just installed it on a new computer but the two scripts added for my partitions in /etc/cron.weekly are not made executable. Is that intentionally and will cron run them?

**Comment by cdysthe** [comment]
I'm on Ubuntu 16.04 x64 and no, they are not executable nor being run.

**Comment by chmatse** [comment]
Should be fixed in [c7fa5b4](https://github.com/chmatse/SSDcronTRIM/commit/c7fa5b4928b369fab9d83c1b426826b18dacb3ab). Thank you Christian!

**Comment by cdysthe** [comment]
Hi,

  

Yes it's fixed. Thank you so much! :)

  
//Christian - Get Vivaldi: https://vivaldi.com  

On Jun 8 2016, at 5:21 pm, Matthias Egger &lt;notifications@github.com&gt;
wrote:  

> Should be fixed in [c7fa5b4](https://github.com/chmatse/SSDcronTRIM/commit/c
7fa5b4928b369fab9d83c1b426826b18dacb3ab). Thank you Christian!

>

> —  
You are receiving this because you commented.  
Reply to this email directly, [view it on GitHub](https://github.com/chmatse/S
SDcronTRIM/issues/7#issuecomment-224732071), or [mute the thread](https://gith
ub.com/notifications/unsubscribe/ABOMB4ZS8IZFsB3ed38jvOT2pdZCoCjfks5qJzJKgaJpZ
M4IxaEk).![](https://github.com/notifications/beacon/ABOMB4nKQgF-
RY7ap5A32kfQ2Y3bGBizks5qJzJKgaJpZM4IxaEk.gif)

**Comment by cdysthe** [comment]
Confirmed fixed. Thanks!
