### ISSUE TITLE
ERROR: Is the disk really an SSD Disk?

### ISSUE THREAD

**Issue by renee77** [chmatse/SSDcronTRIM#8]
Hi,
I installed gentoo on a crucial m500, I used lvm over encryption. I gave kernel trim command, but this script gives this error;
ERROR: You have specified / in SSD_MOUNT_POINTS but
ERROR: it looks like the disk itself does not support any TRIMMING.
ERROR: Is the disk really an SSD Disk?

I am fairly new to this all so maybe I am overlooking something? Do you have any ideas?

Kind regards Eva

**Comment by chmatse** [comment]
The script - at the end - is only a big wrapper for the fstrim command. fstrim only works if the used mountpint also supports trimming. Therefore the script tests if the given partition supports trimming, which in this case failed.

You can manually do this check.

Login as root on your gentoo machine and get the device for your mountpint '/'.
`# mount|grep ' / '`

In my case i get the following output:
`/dev/sdb4 on / type ext4 (rw,noatime,data=ordered)`

which means, my '/' Partition is on device /dev/sdb4.
Then check with hdparm if it supports trim:

```
 # hdparm -I /dev/sdb4|grep -i trim
           *    Data Set Management TRIM supported (limit 16 blocks)
           *    Deterministic read ZEROs after TRIM

```
As you can see, trim is supported. If there is no output, this means the partition does not support trimming and therefore fstrim can not trim anything, which then means, my script would not work at all on that particular partition.

What could be the reason? Since you mentioned lvm and encryption (LUKS/dm-crypt) you may have not enabled Trimming on any involved layer. See [this link](http://blog.neutrino.es/2013/howto-properly-activate-trim-for-your-ssd-on-linux-fstrim-lvm-and-dmcrypt/) which explains more. But make sure you really know what you do, because activating trimming on a encryted volume could be a real [security issue](http://asalor.blogspot.ch/2011/08/trim-dm-crypt-problems.html) which renders the encryption worthless!

Another reason could be, that you have to make sure the SATA Ports are set to AHCI in the BIOS (as [mentioned here](http://forum.crucial.com/t5/Crucial-SSDs/M500-Garbage-Collection-vs-Trim/td-p/130610).

Hope this helps.

Best regards
Matthew
